# Generated by Django 3.0.7 on 2020-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
