# Generated by Django 3.0.7 on 2020-07-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200714_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='plan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='sub_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
