# Generated by Django 3.0.7 on 2020-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='key',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
