# Generated by Django 3.0.7 on 2020-07-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200721_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='payment_status',
        ),
    ]
